services:
  db:
    image: postgres:16
    container_name: ppp_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: devdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: ppp1_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  nestjs_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src:z
      - ./package.json:/app/package.json:z
      - ./nest-cli.json:/app/nest-cli.json:z
      - ./tsconfig.json:/app/tsconfig.json:z

    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - db

  llm_service:
    build:
      context: ./LLM-service
      dockerfile: Dockerfile
    container_name: llm_service
    restart: always
    volumes:
      - ./LLM-service:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5674:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  notification_service:
    build:
      context: ./notification-service  # Path to your notification service
      dockerfile: Dockerfile
    container_name: notification_service
    restart: always
    env_file:
      - ./notification-service/.env
    ports:
      - "3002:3002"  # Different port than your main app
    volumes:
      - ./notification-service:/app:z
      - /app/node_modules
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest


volumes:
  pgdata:
  pgadmin_data:
